### ISSUE TITLE
Segmentation fault with PHPUnit

### ISSUE THREAD

**Issue by deeky666** [nikic/scalar_objects#13]
I noticed that scalar_objects doesn't play very nicely with PHPUnit. Each time a `NOTICE`, `WARNING`, `ERROR` etc. is raised inside a scalar type handler from a native PHP function, PHPUnit tests segfault.
I provided an [example repo to reproduce this](https://github.com/deeky666/scalar-objects-sandbox). Just run the test suite and you'll see.
Does it fall under the "limitations" described in the README or is it a bug that can be fixed?
I tested this with PHP 5.5 and traced the segmentation fault down to [this line](https://github.com/php/php-src/blob/php-5.5.12/Zend/zend_API.c#L237): `Program received signal SIGSEGV, Segmentation fault.`

**Comment by nikic** [comment]
The new approach using an extra param is implemented now, so array callbacks should now work properly.
