### ISSUE TITLE
Scalar Class in Native C Code, how to get it to work with Scalar Object Extension?

### ISSUE THREAD

**Issue by HallofFamer** [nikic/scalar_objects#22]
Well I am writing an extension called scalar_classes that will be dependent on this scalar_objects extension. One issue I am thinking about is that, how will the object pointer work internally with scalar objects? Lets say I usually use this expression obj = getThis() to fetch the object to operate in a method, but with scalar objects it's a bit confusing since the pointer 'this' will not point to an object, but a scalar. I wonder how to get this to work, do you know how I can get started on this? 

Or I can use an example here. From this scalar objects experimental API(written in PHP though), they have a method NumberHandler::abs(), which looks like this below:

    public function abs(){
         return abs($this);
    }

How to translate this into native C code? Would you mind giving an example here? I hope this wont be too difficult or tedious, I thought the example above was simple enough since it merely calls a PHP built-in function. I just want to get a sense of how the 'this' pointer works internally with scalar object, as opposed to other PHP objects. Thanks.

**Comment by HallofFamer** [comment]
Update: I tried to implement a NullObject class in native C code at first, but it already was giving me some headache. The methods are called normally when I just instantiate a NullObject class using $var = new NullObject(). But when I register it as scalar object handler, it will give me a 'Non-static method cannot be called statically' error. This is strange, what is the cause of this and is there a way to get by the issue?

**Comment by nikic** [comment]
@HallofFamer It may well be that this extension currently doesn't work with internal methods (they have a few more restrictions about `$this` usage). Try adding a `ZEND_ACC_ALLOW_STATIC` flag to the method, maybe it'll work ;)

I've been planning to rewrite this ext to not use `$this` and instead pass an extra parameter with the scalar, but didn't yet find the time. Will do this for the PHP 7 port for sure.

**Comment by HallofFamer** [comment]
@nikic: Thanks, it did fix the issue for NullObject class. It threw a strict standard warning but I could get by this by turning off error display for strict standards. Not an ideal way, but will work for PHP 5 as it is now.

And there's indeed another issue though. For NullObject it will not be a problem as it holds no scalar value so all methods will return constant values such as True, Null or 'Null'. Now imagine an IntegerObject, in which the scalar data needs to be sent to another internal function(such as IntegerObject::abs() for abs($this)). Is there a way for me to retrieve the scalar value? I think zval *obj = getThis() will not work, right? So is there another way to achieve this?

And thanks, I am very excited to the PHP 7 port, especially considering that more syntax sugar will be added, such as "my string"->length() and $array->sort().

**Comment by HallofFamer** [comment]
umm it does appear that zval *obj = getThis() will not return the pointer of the scalar data. It seems that this line was why internal function wont work properly with scalar objects extension by default:

'''
	if (fbc->type == ZEND_INTERNAL_FUNCTION) {
             obj = NULL;
        } else {
             Z_ADDREF_P(obj);
        }

So is there a way to fix this behavior? I know there was a good reason why internal function was disabled by default since they assume $this to be an object and there's no way to alter such behavior unless the core zend engine is modified. Still, there's gotta be a way to workaround, as in my internal functions I should still have a way to retrieve the scalar data value, operate on it and return a different value, right? Maybe just not through getThis(), but it should be available in some other ways. Can you maybe give a clue where I should look into? Thanks.

**Comment by HallofFamer** [comment]
umm so can you possibly give some clues on what I can look for to retrieve the value of scalar in a PHP method defined internally?

**Comment by nikic** [comment]
I've updated the ext to use a new approach which does not use `$this` and passes an extra (first) parameter instead. Can you try if it works now?

**Comment by HallofFamer** [comment]
@nikic:

Thanks, the new version works, I managed to declare an abs method on IntObject, and its doing its job! I dont quite understand why the methods now need to be declared static, is there a reason for this? 

I found that even if my methods are not static, it will still work so long as I add the flag ZEND_ACC_ALLOW_STATIC in its zend_function_entry, the method will work as normally. Its kinda interesting, although the strict standards message is kinda annoying.

**Comment by nikic** [comment]
> I dont quite understand why the methods now need to be declared static, is there a reason for this? 

The handler method no longer has a `$this`, so the call happens statically. As such it's also necessary to declare the method as static, otherwise you'll get those strict standards notices.
