### ISSUE TITLE
Construct inline object syntax

### ISSUE THREAD

**Issue by ParkFramework** [nikic/scalar_objects#26]
Probably better to implement - construct inline object syntax?
Syntex should look like PHP arrays and JSON.

Example:
```php

$object = 
{
   "key" => $value
};

API
$object->keys(); $object->split(); $object->join();
```

**Comment by nikic** [comment]
This feature is outside the scope of this extension -- it's not possible to implement that kind of syntax from an extension, it requires a language parser patch.
