### ISSUE TITLE
Does __callStatic() magic method works with scalar objects?

### ISSUE THREAD

**Issue by HallofFamer** [nikic/scalar_objects#28]
I know in the latest version of scalar objects, the methods need to be declared static, with $self as first parameter passed to each method representing the string itself. Now I have a question regarding this change, which is about __callStatic(). As you see in PHP magic methods require specific signature(argument list),  in this case it is $name and $arguments. 

If I use it in scalar objects, there is a problem as the first parameter needs to be $self. So can I use __callStatic() for scalar objects? I just want to change the fatal error 'call to methods on nonobject' to an exception with message 'call to undefined method on int/string/array'. So does __callStatic() work now? Or is it possible to make it work with scalar objects in future if its not?

**Comment by nikic** [comment]
From a quick test __callStatic() works fine. The $self parameter will simple be the first element of $args. Example:

```php
<?php

register_primitive_type_handler('string', 'StringHandler');

class StringHandler {
    public static function __callStatic($name, $args) {
        var_dump($name, $args[0]);
    }
}

$str = "foo";
$str->unknown();
```

This will print out "unknown" and "foo".
