### ISSUE TITLE
Does it support php 7.1?

### ISSUE THREAD

**Issue by jens1o** [nikic/scalar_objects#31]
I saw that you added tests for php 7.1, but in the readme it says:

> This extension supports PHP versions 5.4, 5.5, 5.6 and 7.0.

What's true?

**Comment by jens1o** [comment]
Sadly, it doesn't support php 7.1 with the latest php 7 build, but there is no build for 7.1...

**Comment by nikic** [comment]
@weltling Can you please kick off a new Windows build for this extension?

**Comment by jens1o** [comment]
@nikic So it's supporting it? Nice! Maybe update the readme?

**Comment by weltling** [comment]
@nikic invoked the build, some are uploaded to http://windows.php.net/downloads/pecl/snaps/scalar_objects/20170414/ already. While on it, also triggered the build of latest ext/ast snap :) Both should be done within some hours.

Cheers.

**Comment by jens1o** [comment]
Thanks, do I need to watch out for something else @weltling ?

**Comment by weltling** [comment]
@jens1o not sure to understand the question. You can ping anytime if some ext is missing, otherwise the latest scalar_objects builds are already uploaded.

Thanks.

**Comment by jens1o** [comment]
Nah, wether I need to look after some special, since this is not a automatic build. Thanks for the help!

**Comment by jens1o** [comment]
Works, thanks! Is this build automatic scheduled when there are code changes?

**Comment by weltling** [comment]
Nope. Currently release builds are only done for PECL, otherwise on demand.

Thanks.

**Comment by nikic** [comment]
@weltling Thanks for the builds!

@jens1o I've update the README in https://github.com/nikic/scalar_objects/commit/ec7e558f20981f0a21f07bd2fa3a52033d3c1a82 :)

**Comment by HallofFamer** [comment]
So the windows version for scalar objects is already on PECL? How about the linux version?

**Comment by jens1o** [comment]
@HallofFamer You can build it yourself.

**Comment by ParkFramework** [comment]
@HallofFamer I advise you to turn to @remicollet for help, he is a package wizard :)
https://forum.remirepo.net/viewforum.php?id=5
