### ISSUE TITLE
Is it possible to hook closures?

### ISSUE THREAD

**Issue by zhujinxuan** [nikic/scalar_objects#35]
Hi, Thank you for this amazing plugin.

I am thinking whether there is possibility to make the fp practically in PHP with this plugin.  For example, perhaps we can have 

```
$aTob = function () {....};
$a->fmap($z);
```

to have `(a -> b) -> f a -> f b`.  If we can have 
1. scalar hook is localized per namespace
2. closure is hookable (through we can hook some shape of array like [$closure, ...$args] instead) 

Perhaps we can mimic some Functor attributes in php.  Then experimenting on some other workflow control is possible.

**Comment by nikic** [comment]
This is not possible -- closures are objects, and this extension only allows hooking everything apart from objects.

What this effectively wants is an "extension methods" feature, which allows adding additional methods to a class outside it's declaration. I think that's an interesting feature (if done right, specifically it must use some kind of per-file import of visible extension methods) but out of scope for this extension.
