### ISSUE TITLE
Scalar objects extension does not work with constants

### ISSUE THREAD

**Issue by HallofFamer** [nikic/scalar_objects#42]
Well I have an array method merge which does something like $array->merge($array2), and merging two class constants will fail:
  
    self::ARRAY->merge(self::ARRAY2);       //syntax error

The workaround is to define them as private instance variables:

    $this->array->merge($this->array2);     //ok

But it doesnt seem as good and elegant to me as constants, since these arrays are meant to be constant and immutable. Is there a way to fix this?

**Comment by nikic** [comment]
This is supported in PHP 8.

**Comment by HallofFamer** [comment]
Thats great to know. How about operation on integers for PHP 8? Do we still need something like this :

(2)->timesRepeat(function($i){ echo $i; });

Or the below syntax is now supported? 

2->timesRepeat(function($i){ echo $i; });
