### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by lopesrichard** [nikic/scalar_objects#45]

**Comment by nikic** [comment]
I just checked, this project still works fine on PHP 8.1 and PHP 8.2-dev.

**Comment by HallofFamer** [comment]
I dont think the project is dead, but there aint significant progress in the direction developers want to see either. Is there plan to add it to PECL one day? Also maybe eventually, someone will draft a RFC for scalar objects, if one day PHP considers adding extension methods like C#. I feel the syntax of C#'s extension methods is quite similar to how scalar objects work.
