### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by CHH** [nikic/scalar_objects#6]
I have this code, running it with 5.4.9 and the scalar_objects extension makes a "Segmentation Fault: 11" error.

```php
<?php

namespace arrays;

class ArrayHandler
{
    function length()
    {
        var_dump($this);
        return count($this);
    }
}

register_primitive_type_handler('array', '\arrays\ArrayHandler');

$a = ['foo'];

var_dump($a->length());
```

**Comment by nikic** [comment]
Closing as whatever the issue was, it likely doesn't apply anymore to the current implementation.
